import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"], // choose what you need
});


export const metadata: Metadata = {
  title: "OYINLOYE OYINLADE PHILEMON- Porfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      
    >
      <body className={`min-h-full flex flex-col ${inter.className}`}>{children}</body>
    </html>
  );
}
